### ISSUE TITLE
meow

### ISSUE THREAD

**Issue by diamondnyav** [hatkidchan/conky-nso#1]
@hatkidchan :pleading_face:

**Comment by hatkidchan** [comment]
@diamondnyav :pleading_face:

**Comment by hatkidchan** [comment]
so what's your problem?

**Comment by diamondnyav** [comment]
uhhhhhhhhhhhhh none but I can be your problem :pleading_face:

**Comment by hatkidchan** [comment]
yes please, but what's your problem with ummm, this

**Comment by diamondnyav** [comment]
like really none 
I just wanted to @ you because you said not to :innocent:

**Comment by hatkidchan** [comment]
![:akko_woozy:](https://pl.salushnes.solutions/emoji/akko/akko_woozy.png)

**Comment by hatkidchan** [comment]
closed as meowsolved
